---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLRENDQWhBQ0NRQ1c5QWIzYjFKRGdUQU5CZ2txaGtpRzl3MEJBUXNGQURCSE1Rc3dDUVlEVlFRR0V3SkQKVGpFTE1Ba0dBMVVFQ0F3Q1NFSXhDekFKQmdOVkJBb01BbEZETVI0d0hBWURWUVFEREJWcmRXSmxMV1YyWlc1MApjeTFoWkcxcGMzTnBiMjR3SGhjTk1qQXdOREkwTURnek16QXpXaGNOTkRjd09URXdNRGd6TXpBeldqQmxNUXN3CkNRWURWUVFHRXdKRFRqRUxNQWtHQTFVRUNBd0NTRUl4Q3pBSkJnTlZCQW9NQWxGRE1Ud3dPZ1lEVlFRRERETnIKZFdKbExXVjJaVzUwY3kxaFpHMXBjM05wYjI0dWEzVmlaWE53YUdWeVpTMXNiMmRuYVc1bkxYTjVjM1JsYlM1egpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzBhQVVxWHFwK2RtcDNVR0svCndITWM0dG8wZTFkMzVqYTV5R0dlMG5PRm1XcG1QaVVxZklDR1VaYXlQdUJranhCbk4vSkdRSVpyazFGRk83eWwKNHZZSVpINVdXdTFZNG41MytTRjBIeXRlWGZzRUo4amNFc0RWWURYbHR4ZjIxbWYydmhRUU9TdW4wODRCSVlzbwpkbGFhazBiTUFiQ3o1VnVKRWsxRlNLa0tKYWtWazlwTVV2VlI5MGl0RW0zZjZjbVhLRWZqV0xmV21tWTYvcTNsCkxIcVBSSTRZR1NselFQdXFtQmEzTmlNY1prenh4U2QvZWZFQzVIZkJ0cFkyT0ZpNkRRVVBNY255bUtVSytFYkYKNmplNnBRdmR3MzFJOE1yUVNpNnllMGhrWWNYUEZCclVDVlZFUDREWXdGQ1B6VFJUQmc5SFRqUzV6RlpTOTQvLwp2Rk45QWdNQkFBRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBT2VsUzMyYWc5Zm9aVFpFUGJnM0JBWFJ0OGEzCnMzakk0enZibGR3alFmbzJjYXR2enA2ZE5Jdy8xUDdpR0Y3dVhGdjVMc2RId21VczhPUExsU1VGSVlJTnEzUysKOTZod29yV2V3dW1YS1ZkcDFtT2R4aWpmYjZFeU90alVibThDbGR4WHA2T1dsdjByWkZFbGxpRTBLcEVPSWRDbwpoMUtHS1BqME96MC9SNlBxajIvSnByRnpxQlF0NHQveWJoeVRDenVMdUEyN1Zld1FlR1JyNU5MZzJ4YzhwRVp4CnFmM2pUVFpCTm5FeitjdkdqenowdlJQSmI2UGRFY2FEZzNOeHN3QWdyblhqQndSSzcwNHBhU3g4bXJhdVZLVm8KNkpVN2JiTGprSWJVUlp1SlhCai9xTDJWTmFMZzgxZ28vcVlGNzArTVluSUluT0NaNmpURXdtY1dMdEE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdEdnRktsNnFmblpxZDFCaXY4QnpIT0xhTkh0WGQrWTJ1Y2hobnRKemhabHFaajRsCktueUFobEdXc2o3Z1pJOFFaemZ5UmtDR2E1TlJSVHU4cGVMMkNHUitWbHJ0V09KK2Qva2hkQjhyWGwzN0JDZkkKM0JMQTFXQTE1YmNYOXRabjlyNFVFRGtycDlQT0FTR0xLSFpXbXBOR3pBR3dzK1ZiaVJKTlJVaXBDaVdwRlpQYQpURkwxVWZkSXJSSnQzK25KbHloSDQxaTMxcHBtT3Y2dDVTeDZqMFNPR0JrcGMwRDdxcGdXdHpZakhHWk04Y1VuCmYzbnhBdVIzd2JhV05qaFl1ZzBGRHpISjhwaWxDdmhHeGVvM3VxVUwzY045U1BESzBFb3VzbnRJWkdIRnp4UWEKMUFsVlJEK0EyTUJRajgwMFV3WVBSMDQwdWN4V1V2ZVAvN3hUZlFJREFRQUJBb0lCQUdydmliaE91dU1SVUJSLwpXcmxzMnc4UlRPUjFCQ2ozRmhOVHVzSEkzMThlekJuazFtVHp2YjlnbDJINnNVb0tIMS8vb3FXUDA5M3FTZTh1CjlLaWordENJdVBaNUdWMXBqQ3VUU2dncC9hd0hLeWFRYXBoQXFYc1JkNEU5NFgrWUliSDVnNjBHSm1GcHhCK1oKZ1lJdmV6QlBBbFVrMzFnVEtRbjhCajkrVFd6TVhSSUJwalBobCtDYURjcmExekEwL0s5RG56Sld6M0IrTHNaagpmZWFxWUtMUjdyenlCSEY3YkpvbjdKMHk2MmF1UEJCVWtMSCtpT0ZQSnZtbXhkS0orbEdiNVJHYjN3cDJLNWU5ClI1SWRHcDFGeDI0ZFgwMXQ0NVJjbzRHUndkMFFLeFk4MSt3M3ZFYW93c0lRVlVnWStnRUJTZWR3TzhVTVcrWmQKYVIzTXFrRUNnWUVBMzExR2FmeVlIandzOFcvZ3hyQ3ViQ292dWt0WGNOSXYrejM5NFVGdXppMUt1QmQ3T0NrRworc3c3MTVTRHlnYitDRStyQ3h5Q294Znc5TjR4SHp2Qk01T0NmSVZOc0tjWFJVY05qMlRDL05YZDFUUHZhamZkCmQvNDg4T3lHR2w2RVhiY2pMRkNLSStXdlBQMG5tdFJpVmN0clZTTzEyS2ZHNlFMQTlrbXF3bTBDZ1lFQXpzUHgKTkU1d2h0N3pBVHBBSzZLOVRuQStmVUE5YXpiQWxHOXkrWnZDTmp5WURPNDB6QmZMWmFOc1F3REdUOFNmbVZ0RwpqYW9MTlBUQUVYYTNYRndIOE1oc0I5T3ZpOVV3R3p5b3EzU25za202SkJtbDZMcEFaaFRRS08ySkIzZGRDK1c1CjVDNGlBRVBZL1RPU1kwbjJqSjNlcy80TzBBN3ZyalRaaUs1dXExRUNnWUJ3MFo0VlBuNWZGeW5rTVF3cGoyZ3EKUGd5cFhoQ21iYVBLbFA4ODNWM29TYndweThKekZWWHZLMlUyZUU4d3BlTjlzeS9EaHZ6OC84UzNDZHRwMlRhMgpwRlVPTEE2WG9XNEJrZWZwZTQxNVExU3VzWExHQmIyWk5CTDM1WisraGVyNW90empMekwyK3JaT2FkZXRQb1VFCnJLQmorb3VKQ1FWUkFCRVMxUmFvNlFLQmdDTklIaTJOd1BmU3JXYWxPUFA1TmhKZlp0cGFqdUJ2bkZiMzJZZXMKUTJ5YjFGcElmMnZnRjQ0RlgrRGpEZlBvbWs5QjJ2MHJhZlFrVzIzZmN4Um9nOVpiYk11OUhIUmc4VytFWDBlNgpoUzhRRTVvN1lpc2ZOUVAyUXpyb3BYeEhxdkh2eGxPZ1o1N2g5UEhuemUveFhBZk1uSWJjTUV6aWI1V3JZUDlJCnZJdXhBb0dCQUk5aUZERys2MTVJWWhyTFhlVEh6YjV3UkVlcjZVRzlydlFtMmN1NmlGTkF6OUhJbUJBeG8vNTMKS25sRmQvcmhDcUxUTTJDZlhHSzcvSnozV1hFaVA1Ni9mc1pPd2tiNklkQTF0aGUrRVVjU28wWjFaWnpPNmE0dApGemJLSzUvKzRWNDRTTUdLWGVKSlZDRk9RUlFTOGd0ZjIrbW9KUStNNVJha0YraUVkU0haCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: admission
  namespace: system
type: Opaque
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-mutate
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaRENDQWt5Z0F3SUJBZ0lKQUpxYlYrTnBjeW5OTUEwR0NTcUdTSWIzRFFFQkN3VUFNRWN4Q3pBSkJnTlYKQkFZVEFrTk9NUXN3Q1FZRFZRUUlEQUpJUWpFTE1Ba0dBMVVFQ2d3Q1VVTXhIakFjQmdOVkJBTU1GV3QxWW1VdApaWFpsYm5SekxXRmtiV2x6YzJsdmJqQWVGdzB5TURBME1qUXdPRE16TUROYUZ3MDBOekE1TVRBd09ETXpNRE5hCk1FY3hDekFKQmdOVkJBWVRBa05PTVFzd0NRWURWUVFJREFKSVFqRUxNQWtHQTFVRUNnd0NVVU14SGpBY0JnTlYKQkFNTUZXdDFZbVV0WlhabGJuUnpMV0ZrYldsemMybHZiakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUApBRENDQVFvQ2dnRUJBT29pRXp5ZUtxRnhwQ1czWEVQaHpud2pJS0I0ekRQd01qaDdjR3pyMUo2VFY5bitYSVpVCkpxcm1lSWZkelloejBhQVpMM2tVenZERVZ0TWVUNExiUG14V0V1VUkvRHdjcExGUjBZQzVkWnRHeFpEQk9IakUKa1NndXA2enJPUTFEa1FtamZ5cTVialpFSzJnd1YxZk5FZTc0SXlyUmsreWlHTzJmT0lETWJ0cndnZy9nckVIWAo5cnFqUk1BQVhoQkdCUjFpUzhhellUM2RkaHNvajdwQlM2WnFONjRIR2JTYXg1QVViQy9vbS9IaEZvVDlPSWNnClQvdXVYVVZqTFlHVVowRzEyZi9SM3BuL09waGUrTDNjbWdibUp1VXEwQit6RTByQTNTYmNzbWxMQ1JoS2htVlYKZ29WK0wraU1Xdzh3bHdNd0poRnVVY1BtRjhEaEkvL1RiRnNDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkxJNwo3K1JxNHRJOVQyeCsxektmTFZ4RmJPQUNNQjhHQTFVZEl3UVlNQmFBRkxJNzcrUnE0dEk5VDJ4KzF6S2ZMVnhGCmJPQUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTGJEUFhaOUpOTFAKSGVOdDJCc3VSMWFGMGpYTWRMUC9GWHFqN01IWnV0c3B2RWFXNDh1bU14a1Y2c0sxOHB5Z2QvVWZ6S3NTOEFidApOQ0Q2K3p4clZ6bTVmalF6c2JUWEtXcDdseHNnZ0VuQXFWTlo0Qm1yNHpJYVRySE95R1dVNHRmL2czT2F1YjJxCnprd05yRGFEWi8yWDZIT1pONHFKSitXMEZqakxkNmJ3M3B6bGgyZlFTNFBIdlZFVTZ5UHlBV2dLb2FpZ0hnTmMKd2h5ZEJZenFSeWFVZWJsSzZOVEFKczJaMkd2ZVZjUS92V1paYzJQU2lhMVQ5bjNBelBVQWtBVTQ3UzVmaEJGVAptMjhkeHIxQVIzbVdMYjVqZDNkQkJiS2FMWDBoeENJeU5ndzVhdHpLTjR6QXlTOTBVanppWm42S1h6ekxLZ0dqCm02MWM2VVQyT1NVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: $(ADMISSION_SERVICE_NAME)
      namespace: $(ADMISSION_SERVICE_NAMESPACE)
      path: /mutate-events-kubesphere-io-v1alpha1-rule
  failurePolicy: Fail
  name: mrule.kb.io
  rules:
  - apiGroups:
    - events.kubesphere.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rules

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-validate
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaRENDQWt5Z0F3SUJBZ0lKQUpxYlYrTnBjeW5OTUEwR0NTcUdTSWIzRFFFQkN3VUFNRWN4Q3pBSkJnTlYKQkFZVEFrTk9NUXN3Q1FZRFZRUUlEQUpJUWpFTE1Ba0dBMVVFQ2d3Q1VVTXhIakFjQmdOVkJBTU1GV3QxWW1VdApaWFpsYm5SekxXRmtiV2x6YzJsdmJqQWVGdzB5TURBME1qUXdPRE16TUROYUZ3MDBOekE1TVRBd09ETXpNRE5hCk1FY3hDekFKQmdOVkJBWVRBa05PTVFzd0NRWURWUVFJREFKSVFqRUxNQWtHQTFVRUNnd0NVVU14SGpBY0JnTlYKQkFNTUZXdDFZbVV0WlhabGJuUnpMV0ZrYldsemMybHZiakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUApBRENDQVFvQ2dnRUJBT29pRXp5ZUtxRnhwQ1czWEVQaHpud2pJS0I0ekRQd01qaDdjR3pyMUo2VFY5bitYSVpVCkpxcm1lSWZkelloejBhQVpMM2tVenZERVZ0TWVUNExiUG14V0V1VUkvRHdjcExGUjBZQzVkWnRHeFpEQk9IakUKa1NndXA2enJPUTFEa1FtamZ5cTVialpFSzJnd1YxZk5FZTc0SXlyUmsreWlHTzJmT0lETWJ0cndnZy9nckVIWAo5cnFqUk1BQVhoQkdCUjFpUzhhellUM2RkaHNvajdwQlM2WnFONjRIR2JTYXg1QVViQy9vbS9IaEZvVDlPSWNnClQvdXVYVVZqTFlHVVowRzEyZi9SM3BuL09waGUrTDNjbWdibUp1VXEwQit6RTByQTNTYmNzbWxMQ1JoS2htVlYKZ29WK0wraU1Xdzh3bHdNd0poRnVVY1BtRjhEaEkvL1RiRnNDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkxJNwo3K1JxNHRJOVQyeCsxektmTFZ4RmJPQUNNQjhHQTFVZEl3UVlNQmFBRkxJNzcrUnE0dEk5VDJ4KzF6S2ZMVnhGCmJPQUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTGJEUFhaOUpOTFAKSGVOdDJCc3VSMWFGMGpYTWRMUC9GWHFqN01IWnV0c3B2RWFXNDh1bU14a1Y2c0sxOHB5Z2QvVWZ6S3NTOEFidApOQ0Q2K3p4clZ6bTVmalF6c2JUWEtXcDdseHNnZ0VuQXFWTlo0Qm1yNHpJYVRySE95R1dVNHRmL2czT2F1YjJxCnprd05yRGFEWi8yWDZIT1pONHFKSitXMEZqakxkNmJ3M3B6bGgyZlFTNFBIdlZFVTZ5UHlBV2dLb2FpZ0hnTmMKd2h5ZEJZenFSeWFVZWJsSzZOVEFKczJaMkd2ZVZjUS92V1paYzJQU2lhMVQ5bjNBelBVQWtBVTQ3UzVmaEJGVAptMjhkeHIxQVIzbVdMYjVqZDNkQkJiS2FMWDBoeENJeU5ndzVhdHpLTjR6QXlTOTBVanppWm42S1h6ekxLZ0dqCm02MWM2VVQyT1NVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: $(ADMISSION_SERVICE_NAME)
      namespace: $(ADMISSION_SERVICE_NAMESPACE)
      path: /validate-events-kubesphere-io-v1alpha1-rule
  failurePolicy: Fail
  name: vrule.kb.io
  rules:
  - apiGroups:
    - events.kubesphere.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rules
---
apiVersion: v1
kind: Service
metadata:
  name: admission
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: $(OPERATOR_NAME)