apiVersion: events.kubesphere.io/v1alpha1
kind: Exporter
metadata:
  name: exporter
  namespace: system
spec:
  image: exporter
  resources: {}
#    limits:
#      cpu: 200m
#      memory: 500Mi
#    requests:
#      cpu: 20m
#      memory: 50Mi
  sinks:
    stdout: {}
    webhooks:
    - service:
        namespace: system
        name: ruler
        port: 8443
        path: /events