apiVersion: events.kubesphere.io/v1alpha1
kind: Ruler
metadata:
  name: ruler
  namespace: system
spec:
  image: ruler
  sinks:
    alertmanager:
      namespace: kubesphere-monitoring-system
      name: alertmanager-main